Layer Cluster Generation
mitre-attack/mitreattack-python pull request #30
Opened 2021-08-25 12:52 UTC by ArtificialErmine

Adds the ability to generate sets of layers automatically. 

Closes #21

2021-08-25 12:54 UTC, ArtificialErmine commented
This instance of it is rather slow on the extreme end (groups in enterprise can run about 2 hours according to the estimate), but unfortunately I haven't found any ways to quickly speed it up (there doesn't seem to be any obvious places we can cache results for the moment). If you target an output that is much more limited, like groups for mobile, the output gets generated at reasonable speeds.

2021-09-13 15:27 UTC, isaisabel requested changes
The general approach looks solid and I like the fact that it's just batch running existing code, very clean and simple approach. Most of my comments are regarding documentation/naming of functionality for clarity of the user. 

In terms of performance improvements, [this block](https://github.com/mitre-attack/mitreattack-python/blob/master/mitreattack/navlayers/generators/usage_generator.py#L65-L68) can instead of running a filter function iterate over the mapped IDs and use a `self.source_handle.get(id)` to actually get the mapped object. I believe [stix2's `get` function runs in constant time](https://github.com/oasis-open/cti-python-stix2/blob/master/stix2/datastore/memory.py#L260-L274) which is better than the Filter function which must iterate the entire contents of the data source.

Pseudocode:
```python
results = []
for r in related:
    mapped = self.source_handle.get(r.related)
    if mapped.type != 'attack-pattern': continue
    results.append(mapped)
return remove_revoked_deprecated(results), obj
```

Efficiency comparison (where N is the number of objects in the dataset and the majority of objects are relationships):
- Before: All Objects * Relevant Relationships * All Objects = `O(N^3)`  
- After: All Objects * Relevant Relationships = `O(N^2)`

(This particular big-O analysis is a bit tricky so that my be a bit off, but I think it's something along that line. At the very least it will be reducing one iteration of the full dataset per output layer)

2021-09-14 14:27 UTC, ArtificialErmine commented on mitreattack/navlayers/generators/sum_generator.py
> +        Generate a layer
Yeah, that documentation was definitely off.

2021-09-14 14:28 UTC, ArtificialErmine commented on mitreattack/navlayers/generators/sum_generator.py
> +class SumGenerator:
Batch makes sense to me - I'll adjust things appropriately.

2021-09-14 14:30 UTC, ArtificialErmine commented on mitreattack/navlayers/layerGenerator_cli.py
> +                            'different instance of the target type.')
Batch definitely sounds better. I'll adjust everything to that, and rename things to properly reference layers vs matrices.

2021-09-14 14:36 UTC, ArtificialErmine commented on mitreattack/navlayers/layerGenerator_cli.py
> +    parser.add_argument('-o', '--output', help='Path to the output layer file (output)', default='generated_layer.json')
That would be a lot cleaner... I'll see if I can put something together.

2021-09-14 15:51 UTC, ArtificialErmine commented
> The general approach looks solid and I like the fact that it's just batch running existing code, very clean and simple approach. Most of my comments are regarding documentation/naming of functionality for clarity of the user.
> 
> In terms of performance improvements, [this block](https://github.com/mitre-attack/mitreattack-python/blob/master/mitreattack/navlayers/generators/usage_generator.py#L65-L68) can instead of running a filter function iterate over the mapped IDs and use a `self.source_handle.get(id)` to actually get the mapped object. I believe [stix2's `get` function runs in constant time](https://github.com/oasis-open/cti-python-stix2/blob/master/stix2/datastore/memory.py#L260-L274) which is better than the Filter function which must iterate the entire contents of the data source.
> 
> Pseudocode:
> 
> ```python
> results = []
> for r in related:
>     mapped = self.source_handle.get(r.target_ref)
>     if mapped.type != 'attack-pattern': continue
>     results.append(mapped)
> return remove_revoked_deprecated(results), obj
> ```
> 
> Efficiency comparison (where N is the number of objects in the dataset and the majority of objects are relationships):
> 
> * Before: All Objects * Relevant Relationships * All Objects = `O(N^3)`
> * After: All Objects * Relevant Relationships = `O(N^2)`
> 
> (This particular big-O analysis is a bit tricky so that my be a bit off, but I think it's something along that line. At the very least it will be reducing one iteration of the full dataset per output layer)

So, I tested both approaches with a job that takes about half an hour, and unfortunately, we seem to be at the point where the constant is large enough that the complexity shift doesn't actually make a noticeable difference. In a very rough test, it took just under a minute longer to use `get` than to use filters. I'm going to keep toying with this, but I don't think using `get` is quite as beneficial as we might have hoped.

2021-10-01 14:32 UTC, isaisabel approved these changes
Sad that we couldn't get it to be more efficient but I understand that with the amount of data we're chugging through that may be unavoidable. Overall seems fine as it is currently.

2021-10-01 14:49 UTC, merged